### ISSUE TITLE
Credential function not working

### ISSUE THREAD

**Issue by ralfyang** [Klevry/klevr#133]
![image](https://user-images.githubusercontent.com/4043594/130537174-c153e0a9-3a4e-4084-b84e-41be8fec1a5b.png)
Need to use as a key/value variable like the screen capture.

**Comment by jaehoonkim** [comment]
The added credential can be used in parameters.
![capture-0](https://user-images.githubusercontent.com/2362408/133384234-c0df8879-7017-4ba2-b679-a20f87acc1a0.PNG)

In "command", parameter registered as environmental variable($TASK_ORIGIN_PARAM}) can be used.
![capture-1](https://user-images.githubusercontent.com/2362408/133384267-886eefe6-d2ae-4624-9a30-80a03e120d3e.PNG)
