### ISSUE TITLE
[Agent] Task checker & executer

### ISSUE THREAD

**Issue by ralfyang** [Klevry/klevr#34]

**Comment by junhwani** [comment]
- agent 실행시 command 가져와서 prometheus-operator 실행 확인
- command가 여러번 실행되는 문제 해결 필요함
- manager docker image(커맨드 가져오는 깃헙주소 - http로 수정필요)
- provbee에서 kubectl로 바로 못받아서 /usr/local/bin/kubectl로 받을수있게 함
